### ISSUE TITLE
tidak bisa save configuration

### ISSUE THREAD

**Issue by ridridku** [uasoft-indonesia/badaso#623] opened 2022-03-14 08:28 UTC
![Untitled](https://user-images.githubusercontent.com/15811148/158133513-6ed330a4-dcb7-4f51-b3e6-ef6ced7f4cee.png)

**Comment by rizkiheryandi** [comment] 2022-03-15 05:02
Duplicate of #513

**Closed by rizkiheryandi** 2022-03-15 05:02 UTC
